---
name-template: 'v$NEXT_MINOR_VERSION 🌈'
tag-template: 'v$NEXT_MINOR_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

template: |
  ## Changes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
      - 'dependencies'
  patch:
    labels:
      - 'patch'
  default: patch
exclude-labels:
  - 'skip-changelog'
prerelease: true
