rules:
  secrets-outside-env:
    config:
      allow:
        - UPDATECLIBOT_APP_ID
        - UPDATECLIBOT_APP_PRIVKEY
        - UPDATECLIBOT_APP_INSTALLATION_ID
        - UPDATECLI_UDASH_API_URL
        - UPDATECLI_UDASH_ACCESS_TOKEN
        - UPDATECLI_UDASH_URL
