# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: 'Updatecli Installer'
description: 'Install a specific Updatecli version'
author: 'Updatecli'
branding:
  icon: 'fast-forward'
  color: 'purple'
inputs:
  version:
    description: 'Specify Updatecli version to use. Accepted values are any Updatecli version'
    required: false
    default: "v0.32.0"
runs:
  using: 'node16'
  main: 'dist/index.js'
