policies:
  - name: Local Updatecli Website Policies
    config:
      - updatecli/updatecli.d/
    values:
      - updatecli/values.d/scm.yaml

  - name: Handle Nodejs version in githubaction
    policy: ghcr.io/updatecli/policies/nodejs/githubaction:0.11.0@sha256:164e4ab1e0badc952b5f272d406a201bbb55464262848ab120e29843ab125100
    values:
      - updatecli/values.d/scm.yaml
      - updatecli/values.d/nodejs.yaml

  - name: Update Updatecli policies
    policy: ghcr.io/updatecli/policies/updatecli/autodiscovery:0.8.0@sha256:fee6562ca456331c519a85b74bf5998169fd8b9754bbea13171f53e06e2e5154
    values:
      - updatecli/values.d/scm.yaml

  - name: NPM autodiscovery
    policy: ghcr.io/updatecli/policies/npm/autodiscovery:0.11.0@sha256:884177c126cce170988e3afd1194b1aa1bad0d8fe9aaeea9eaf8038015e50252
    values:
      - updatecli/values.d/scm.yaml
      - updatecli/values.d/npm.yaml

  - name: Handle Updatecli version in GitHub action
    policy: ghcr.io/updatecli/policies/updatecli/githubaction:0.8.0@sha256:a4f4e4fcf0950a0eb359ed0518ef789272ea4db1e0bdba048a3772925b81a7aa
    values:
      - updatecli/values.d/scm.yaml

  - name: Handle GitHub action version update
    policy: ghcr.io/updatecli/policies/autodiscovery/githubaction:0.3.0@sha256:3b5425da2a2a2b89bb69463f1294704c33730358c66140efb93cab14b2868b06
    values:
      - updatecli/values.d/scm.yaml
      - updatecli/values.d/githubaction.yaml

  - name: Update Updatecli version in GitHub action
    policy: ghcr.io/updatecli/policies/updatecli/githubaction:0.8.0@sha256:a4f4e4fcf0950a0eb359ed0518ef789272ea4db1e0bdba048a3772925b81a7aa
    values:
      - updatecli/values.d/scm.yaml
      - updatecli/values.d/githubaction.yaml
