---
name: Updatecli Test
on:
  pull_request:
permissions:
  contents: read
jobs:
  updatecli:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10" # v6.0.3
        with:
          persist-credentials: false
      - name: "Setup updatecli"
        uses: "updatecli/updatecli-action@e71be7554f3f940bc439cf720b3e4e379823c562" # v3.2.0
        with:
          version: "v0.117.1"
      - name: "Test updatecli in dry-run mode"
        run: "updatecli compose diff"
        env:
          # This step is executed in untrusted context. We use a GitHub token with minimal permissions.
          UPDATECLI_GITHUB_USERNAME: ${{ github.actor }}
          UPDATECLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
