---
name: Updatecli Test
on:
  pull_request:
permissions:
  contents: read
jobs:
  updatecli:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10" # v6.0.3
        with:
          persist-credentials: false
      - name: "Setup updatecli"
        uses: "updatecli/updatecli-action@5bda7da77bf4d181bce5f807d73d832b62062acf" # v3.3.0
        with:
          version: "v0.118.0"
      - name: "Test updatecli in dry-run mode"
        run: "updatecli compose diff"
        env:
          # This step is executed in untrusted context. We use a GitHub token with minimal permissions.
          UPDATECLI_GITHUB_USERNAME: ${{ github.actor }}
          UPDATECLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
